workflow:
    - publish

shared:
    image: node:8

jobs:
    main:
        steps:
            - install: npm install
            - test: npm test

    publish:
        steps:
            - install: npm install semantic-release
            - publish: npm run semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
